/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void addShouldAddTwoIntegers(){
        // Set Up
        int expected = 2;
        Library classUnderTest = new Library();

        //Exercise
        int actual = classUnderTest.add(1, 1);

        //Assert
        assertEquals("1 + 1 should equal 2", expected, actual);
    }
}
